sap.ui.define([
], function() {

var QUALITATIVE_PALETTE_BELIZE = {
	"sapUiChartPaletteQualitativeHue1" : "#5899DA",
	"sapUiChartPaletteQualitativeHue2" : "#E8743B",
	"sapUiChartPaletteQualitativeHue3" : "#19A979",
	"sapUiChartPaletteQualitativeHue4" : "#ED4A7B",
	"sapUiChartPaletteQualitativeHue5" : "#945ECF",
	"sapUiChartPaletteQualitativeHue6" : "#13A4B4",
	"sapUiChartPaletteQualitativeHue7" : "#525DF4",
	"sapUiChartPaletteQualitativeHue8" : "#BF399E",
	"sapUiChartPaletteQualitativeHue9" : "#6C8893",
	"sapUiChartPaletteQualitativeHue10" : "#EE6868",
	"sapUiChartPaletteQualitativeHue11" : "#2F6497",
	"sapUiChartPaletteQualitativeHue12" : "#1866b4",
	"sapUiChartPaletteQualitativeHue13" : "#cc4300",
	"sapUiChartPaletteQualitativeHue14" : "#03734d",
	"sapUiChartPaletteQualitativeHue15" : "#d70947",
	"sapUiChartPaletteQualitativeHue16" : "#772acb",
	"sapUiChartPaletteQualitativeHue17" : "#087682",
	"sapUiChartPaletteQualitativeHue18" : "#2531d4",
	"sapUiChartPaletteQualitativeHue19" : "#921473",
	"sapUiChartPaletteQualitativeHue20" : "#3c6372",
	"sapUiChartPaletteQualitativeHue21" : "#d62f2f",
	"sapUiChartPaletteQualitativeHue22" : "#144b7f"
};

var QUALITATIVE_PALETTE_BELIZE_HCB = {
	"sapUiChartPaletteQualitativeHue1" : "#4da2f6",
	"sapUiChartPaletteQualitativeHue2" : "#e8743b",
	"sapUiChartPaletteQualitativeHue3" : "#19a979",
	"sapUiChartPaletteQualitativeHue4" : "#ed4a7b",
	"sapUiChartPaletteQualitativeHue5" : "#945ecf",
	"sapUiChartPaletteQualitativeHue6" : "#13a4b4",
	"sapUiChartPaletteQualitativeHue7" : "#5c66f5",
	"sapUiChartPaletteQualitativeHue8" : "#c63fa4",
	"sapUiChartPaletteQualitativeHue9" : "#6c8893",
	"sapUiChartPaletteQualitativeHue10" : "#ee6868",
	"sapUiChartPaletteQualitativeHue11" : "#387bb7",
	"sapUiChartPaletteQualitativeHue12" : "#0979e8",
	"sapUiChartPaletteQualitativeHue13" : "#df4e07",
	"sapUiChartPaletteQualitativeHue14" : "#03734d",
	"sapUiChartPaletteQualitativeHue15" : "#d70947",
	"sapUiChartPaletteQualitativeHue16" : "#772acb",
	"sapUiChartPaletteQualitativeHue17" : "#087682",
	"sapUiChartPaletteQualitativeHue18" : "#1b28e5",
	"sapUiChartPaletteQualitativeHue19" : "#951475",
	"sapUiChartPaletteQualitativeHue20" : "#3c6372",
	"sapUiChartPaletteQualitativeHue21" : "#d62f2f",
	"sapUiChartPaletteQualitativeHue22" : "#0c5596"
};

var QUALITATIVE_PALETTE_BELIZE_HCW = {
	"sapUiChartPaletteQualitativeHue1" : "#286ac3",
	"sapUiChartPaletteQualitativeHue2" : "#d74114",
	"sapUiChartPaletteQualitativeHue3" : "#057d47",
	"sapUiChartPaletteQualitativeHue4" : "#e11e48",
	"sapUiChartPaletteQualitativeHue5" : "#642eb2",
	"sapUiChartPaletteQualitativeHue6" : "#03778c",
	"sapUiChartPaletteQualitativeHue7" : "#232deb",
	"sapUiChartPaletteQualitativeHue8" : "#9b136f",
	"sapUiChartPaletteQualitativeHue9" : "#395563",
	"sapUiChartPaletteQualitativeHue10" : "#e02e2e",
	"sapUiChartPaletteQualitativeHue11" : "#0d3367",
	"sapUiChartPaletteQualitativeHue12" : "#0e4186",
	"sapUiChartPaletteQualitativeHue13" : "#922707",
	"sapUiChartPaletteQualitativeHue14" : "#014e2b",
	"sapUiChartPaletteQualitativeHue15" : "#92122d",
	"sapUiChartPaletteQualitativeHue16" : "#3b1079",
	"sapUiChartPaletteQualitativeHue17" : "#014956",
	"sapUiChartPaletteQualitativeHue18" : "#0e15a0",
	"sapUiChartPaletteQualitativeHue19" : "#660647",
	"sapUiChartPaletteQualitativeHue20" : "#0e232d",
	"sapUiChartPaletteQualitativeHue21" : "#9e0f0f",
	"sapUiChartPaletteQualitativeHue22" : "#041a38"
};

var SEMANTIC_PALETTE_BELIZE = {
	"sapUiChartPaletteSemanticBadLight3" : "#f99494",
	"sapUiChartPaletteSemanticBadLight2" : "#f66364",
	"sapUiChartPaletteSemanticBadLight1" : "#f33334",
	"sapUiChartPaletteSemanticBad" : "#dc0d0e",
	"sapUiChartPaletteSemanticBadDark1" : "#b90c0d",
	"sapUiChartPaletteSemanticBadDark2" : "#930a0a",
	"sapUiChartPaletteSemanticCriticalLight3" : "#f8cc8c",
	"sapUiChartPaletteSemanticCriticalLight2" : "#f5b04d",
	"sapUiChartPaletteSemanticCriticalLight1" : "#f29b1d",
	"sapUiChartPaletteSemanticCritical" : "#de890d",
	"sapUiChartPaletteSemanticCriticalDark1" : "#c67a0c",
	"sapUiChartPaletteSemanticCriticalDark2" : "#a4650a",
	"sapUiChartPaletteSemanticGoodLight3" : "#a1dbb1",
	"sapUiChartPaletteSemanticGoodLight2" : "#71c989",
	"sapUiChartPaletteSemanticGoodLight1" : "#4cba6b",
	"sapUiChartPaletteSemanticGood" : "#3fa45b",
	"sapUiChartPaletteSemanticGoodDark1" : "#358a4d",
	"sapUiChartPaletteSemanticGoodDark2" : "#2a6d3c",
	"sapUiChartPaletteSemanticNeutralLight3" : "#d5dadc",
	"sapUiChartPaletteSemanticNeutralLight2" : "#bac1c4",
	"sapUiChartPaletteSemanticNeutralLight1" : "#9ea8ad",
	"sapUiChartPaletteSemanticNeutral" : "#848f94",
	"sapUiChartPaletteSemanticNeutralDark1" : "#69767c",
	"sapUiChartPaletteSemanticNeutralDark2" : "#596468"
};

var SEMANTIC_PALETTE_BELIZE_HCB = {
	"sapUiChartPaletteSemanticBad":"#ff5e5e",
	"sapUiChartPaletteSemanticBadDark1":"#ff5e5e",
	"sapUiChartPaletteSemanticBadDark2":"#ff5e5e",
	"sapUiChartPaletteSemanticBadLight1":"#ff5e5e",
	"sapUiChartPaletteSemanticBadLight2":"#db3535",
	"sapUiChartPaletteSemanticBadLight3":"#db3535",
	"sapUiChartPaletteSemanticCritical":"#ffab1d",
	"sapUiChartPaletteSemanticCriticalDark1":"#ffab1d",
	"sapUiChartPaletteSemanticCriticalDark2":"#ffab1d",
	"sapUiChartPaletteSemanticCriticalLight1":"#ffab1d",
	"sapUiChartPaletteSemanticCriticalLight2":"#b67200",
	"sapUiChartPaletteSemanticCriticalLight3":"#b67200",
	"sapUiChartPaletteSemanticGood":"#99cc99",
	"sapUiChartPaletteSemanticGoodDark1":"#99cc99",
	"sapUiChartPaletteSemanticGoodDark2":"#99cc99",
	"sapUiChartPaletteSemanticGoodLight1":"#99cc99",
	"sapUiChartPaletteSemanticGoodLight2":"#5e975e",
	"sapUiChartPaletteSemanticGoodLight3":"#5e975e",
	"sapUiChartPaletteSemanticNeutral":"#ffffff",
	"sapUiChartPaletteSemanticNeutralDark1":"#ffffff",
	"sapUiChartPaletteSemanticNeutralDark2":"#ffffff",
	"sapUiChartPaletteSemanticNeutralLight1":"#ffffff",
	"sapUiChartPaletteSemanticNeutralLight2":"#8c8c8c",
	"sapUiChartPaletteSemanticNeutralLight3":"#8c8c8c"
};

var SEMANTIC_PALETTE_BELIZE_HCW = {
	"sapUiChartPaletteSemanticBad":"#ab0000",
	"sapUiChartPaletteSemanticBadDark1":"#ab0000",
	"sapUiChartPaletteSemanticBadDark2":"#ab0000",
	"sapUiChartPaletteSemanticBadLight1":"#ab0000",
	"sapUiChartPaletteSemanticBadLight2":"#ed0000",
	"sapUiChartPaletteSemanticBadLight3":"#ed0000",
	"sapUiChartPaletteSemanticCritical":"#5c5c00",
	"sapUiChartPaletteSemanticCriticalDark1":"#5c5c00",
	"sapUiChartPaletteSemanticCriticalDark2":"#5c5c00",
	"sapUiChartPaletteSemanticCriticalLight1":"#5c5c00",
	"sapUiChartPaletteSemanticCriticalLight2":"#7b7b00",
	"sapUiChartPaletteSemanticCriticalLight3":"#7b7b00",
	"sapUiChartPaletteSemanticGood":"#006362",
	"sapUiChartPaletteSemanticGoodDark1":"#006362",
	"sapUiChartPaletteSemanticGoodDark2":"#006362",
	"sapUiChartPaletteSemanticGoodLight1":"#006362",
	"sapUiChartPaletteSemanticGoodLight2":"#008785",
	"sapUiChartPaletteSemanticGoodLight3":"#008785",
	"sapUiChartPaletteSemanticNeutral":"#000000",
	"sapUiChartPaletteSemanticNeutralDark1":"#000000",
	"sapUiChartPaletteSemanticNeutralDark2":"#000000",
	"sapUiChartPaletteSemanticNeutralLight1":"#000000",
	"sapUiChartPaletteSemanticNeutralLight2":"#666666",
	"sapUiChartPaletteSemanticNeutralLight3":"#666666"
};

var SEQUENTIAL_PALETTE_BELIZE = {
	"sapUiChartPaletteSequentialHue1Light3" : "#b2d4f5",
	"sapUiChartPaletteSequentialHue1Light2" : "#93bfeb",
	"sapUiChartPaletteSequentialHue1Light1" : "#74abe2",
	"sapUiChartPaletteSequentialHue1" : "#5899da",
	"sapUiChartPaletteSequentialHue1Dark1" : "#367dc4",
	"sapUiChartPaletteSequentialHue1Dark2" : "#1866b4",
	"sapUiChartPaletteSequentialHue2Light3" : "#ffb18a",
	"sapUiChartPaletteSequentialHue2Light2" : "#f3b89b",
	"sapUiChartPaletteSequentialHue2Light1" : "#f08956",
	"sapUiChartPaletteSequentialHue2" : "#e8743b",
	"sapUiChartPaletteSequentialHue2Dark1" : "#da5a1b",
	"sapUiChartPaletteSequentialHue2Dark2" : "#cc4300",
	"sapUiChartPaletteSequentialHue3Light3" : "#8fd1bb",
	"sapUiChartPaletteSequentialHue3Light2" : "#66c2a3",
	"sapUiChartPaletteSequentialHue3Light1" : "#3fb68e",
	"sapUiChartPaletteSequentialHue3" : "#19a979",
	"sapUiChartPaletteSequentialHue3Dark1" : "#0e8c62",
	"sapUiChartPaletteSequentialHue3Dark2" : "#03734d"
};

var SEQUENTIAL_PALETTE_BELIZE_HCB = {
	"sapUiChartPaletteSequentialHue1":"#4da2f6",
	"sapUiChartPaletteSequentialHue1Dark1":"#2d8eed",
	"sapUiChartPaletteSequentialHue1Dark2":"#0979e8",
	"sapUiChartPaletteSequentialHue1Light1":"#6fb4f8",
	"sapUiChartPaletteSequentialHue1Light2":"#95c8fa",
	"sapUiChartPaletteSequentialHue1Light3":"#b4d7fa",
	"sapUiChartPaletteSequentialHue2":"#e8743b",
	"sapUiChartPaletteSequentialHue2Dark1":"#e46121",
	"sapUiChartPaletteSequentialHue2Dark2":"#df4e07",
	"sapUiChartPaletteSequentialHue2Light1":"#ef8d5d",
	"sapUiChartPaletteSequentialHue2Light2":"#f5aa85",
	"sapUiChartPaletteSequentialHue2Light3":"#fcc3a7",
	"sapUiChartPaletteSequentialHue3":"#19a979",
	"sapUiChartPaletteSequentialHue3Dark1":"#0e8c62",
	"sapUiChartPaletteSequentialHue3Dark2":"#03734d",
	"sapUiChartPaletteSequentialHue3Light1":"#3fb68e",
	"sapUiChartPaletteSequentialHue3Light2":"#66c2a3",
	"sapUiChartPaletteSequentialHue3Light3":"#8fd1bb"
};

var SEQUENTIAL_PALETTE_BELIZE_HCW = {
	"sapUiChartPaletteSequentialHue1":"#286ac3",
	"sapUiChartPaletteSequentialHue1Dark1":"#1b57a7",
	"sapUiChartPaletteSequentialHue1Dark2":"#0e4186",
	"sapUiChartPaletteSequentialHue1Light1":"#4880cb",
	"sapUiChartPaletteSequentialHue1Light2":"#6b99d6",
	"sapUiChartPaletteSequentialHue1Light3":"#87acde",
	"sapUiChartPaletteSequentialHue2":"#d74114",
	"sapUiChartPaletteSequentialHue2Dark1":"#b6340d",
	"sapUiChartPaletteSequentialHue2Dark2":"#922707",
	"sapUiChartPaletteSequentialHue2Light1":"#e15f38",
	"sapUiChartPaletteSequentialHue2Light2":"#ee7f5e",
	"sapUiChartPaletteSequentialHue2Light3":"#faa085",
	"sapUiChartPaletteSequentialHue3":"#057d47",
	"sapUiChartPaletteSequentialHue3Dark1":"#036639",
	"sapUiChartPaletteSequentialHue3Dark2":"#014e2b",
	"sapUiChartPaletteSequentialHue3Light1":"#2e9667",
	"sapUiChartPaletteSequentialHue3Light2":"#5aad87",
	"sapUiChartPaletteSequentialHue3Light3":"#87c7aa"
};

	return {
		QUALITATIVE_PALETTE_BELIZE: QUALITATIVE_PALETTE_BELIZE,
		QUALITATIVE_PALETTE_BELIZE_HCB: QUALITATIVE_PALETTE_BELIZE_HCB,
		QUALITATIVE_PALETTE_BELIZE_HCW: QUALITATIVE_PALETTE_BELIZE_HCW,
		SEMANTIC_PALETTE_BELIZE: SEMANTIC_PALETTE_BELIZE,
		SEMANTIC_PALETTE_BELIZE_HCB: SEMANTIC_PALETTE_BELIZE_HCB,
		SEMANTIC_PALETTE_BELIZE_HCW: SEMANTIC_PALETTE_BELIZE_HCW
	};

});